# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

# Comment the following line to switch to the mainstream AudioKit pod
#source 'https://github.com/AudioKit/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AudioKitPlaygrounds' do
  use_frameworks!
  pod 'AudioKit'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end

  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
      end
  end
end
